version: "3.9"

networks:
  blog.test:

services:
  nginx:
    build:
      args:
        user: weybansky
        uid: 1000
      context: .
      dockerfile: docker-files/nginx.dockerfile
    # container_name: nginx
    image: weybansky/nginxssl
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
      - mysql
    networks:
      - blog.test

  mysql:
    image: mysql:5.7.36
    # container_name: mysql
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./docker-files/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - blog.test

  php:
    build:
      args:
        user: weybansky
        uid: 1000
      context: .
      dockerfile: docker-files/Dockerfile
    # container_name: php
    image: weybansky/php82
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
    networks:
      - blog.test

  npm:
    image: node:18.14.2
    # container_name: npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - blog.test
