version: "3.9"

networks:
  blog.test:

services:
  nginx:
    build:
      args:
        user: weybansky
        uid: 1000
      context: .
      dockerfile: docker-files/nginx.dockerfile
    # container_name: nginx
    image: weybansky/nginxssl
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
      - mysql
    networks:
      - blog.test

  mysql:
    image: mysql:5.7.34
    # image: mysql:5.7.36
    # image: mysql:8.0.35
    # image: mysql:8.2
    # container_name: mysql
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./docker-files/mysql572:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ahmarket1
      # MYSQL_USER: root
      # MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD:
      # SERVICE_TAGS: dev
      # SERVICE_NAME: mysql
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      # MYSQL_RANDOM_ROOT_PASSWORD: 
    networks:
      - blog.test

  php:
    build:
      args:
        user: weybansky
        uid: 1000
      context: .
      dockerfile: docker-files/Dockerfile
    # container_name: php
    # image: weybansky/php82-node
    image: weybansky/php73
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
    networks:
      - blog.test

  # npm:
  #   image: node:18.14.2
  #   # container_name: npm
  #   volumes:
  #     - ./:/var/www/html
  #   working_dir: /var/www/html
  #   entrypoint: ["npm"]
  #   networks:
  #     - blog.test
